vich_uploader:
    db_driver: orm

    mappings:
        album_media:
            uri_prefix: /media/albums
            upload_destination: '%kernel.project_dir%/public/media/albums'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'