easy_admin:
  design:
    menu:
      - label: 'Album photo'
        icon: 'newspaper-o'
        children:
          - { entity: 'User', icon: 'id-badge', label: 'Utilisateurs' }
          - { entity: 'Album', icon: 'newspaper-o', label: 'Albums photo' }
          - { route: 'admin_albums_index', icon: 'newspaper-o', label: 'Albums photo' }
          - { entity: 'Family', icon: 'users', label: 'Familles' }
          - { entity: 'Role', icon: 'user-tag', label: 'Rôles' }
          - { entity: 'Media', icon: 'user-tag', label: 'Médias' }
