easy_admin:
  design:
    menu:
      - label: 'Album photo'
        icon: 'newspaper-o'
        children:
          - { entity: 'User', icon: 'user-o', label: 'Utilisateurs' }
          - { entity: 'Album', icon: 'newspaper-o', label: 'Albums photo' }
          - { entity: 'Family', icon: 'user-friends-o', label: 'Familles' }
          - { icon: 'user-friends', label: 'Album', route: 'admin_albums_index' }
          - { icon: 'user-o', label: 'Album', route: 'admin_albums_index' }
