easy_admin:
  design:
    menu:
      - label: 'Album photo'
        icon: 'newspaper-o'
        children:
          - {entity: 'User', icon: 'newspaper-o', label: 'Utilisateurs'}
          - {entity: 'Album', icon: 'newspaper-o', label: 'Album photo'}
